export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_POJECT = 'UPDATE_POJECTS'
export const ADD_POJECTS = 'ADD_PROJECTS'
export const UPDATE_SINGLE_PROJECT = 'UPDATE_SINGLE_PROJECT'
export const ADD_DATA_TO_PROJECT ="ADD_DATA_TO_PROJECT"